# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# IP: ip/invSbox_mem_gen_0/invSbox_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==invSbox_mem_gen_0 || ORIG_REF_NAME==invSbox_mem_gen_0}]

# IP: ip/sbox_mem_gen_0/sbox_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sbox_mem_gen_0 || ORIG_REF_NAME==sbox_mem_gen_0}]
