# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/College/Thesis/AES_2018/AES_After 9_10_2018/aes256_pipeline/aes256_pipeline.srcs/sources_1/ip/data_mem_gen_0/data_mem_gen_0.xci
# IP: The module: 'data_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/College/Thesis/AES_2018/AES_After 9_10_2018/aes256_pipeline/aes256_pipeline.srcs/sources_1/ip/data_mem_gen_0/data_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/College/Thesis/AES_2018/AES_After 9_10_2018/aes256_pipeline/aes256_pipeline.srcs/sources_1/ip/data_mem_gen_0/data_mem_gen_0.xci
# IP: The module: 'data_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/College/Thesis/AES_2018/AES_After 9_10_2018/aes256_pipeline/aes256_pipeline.srcs/sources_1/ip/data_mem_gen_0/data_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
