webtalk_init -webtalk_dir C:/College/Thesis/AES_2018/AES_128/AES_128.sim/sim_1/synth/timing/xsim.dir/test_time_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Aug 30 14:22:37 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1846317" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5a4c118c870850df9f6e6589c4686453" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "21ae8e2c7e604eb5a708990ef9ad1f4e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "9" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "247 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "19 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "186" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "22" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip simprims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "65996_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2646698765 -regid "" -xml C:/College/Thesis/AES_2018/AES_128/AES_128.sim/sim_1/synth/timing/xsim.dir/test_time_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/College/Thesis/AES_2018/AES_128/AES_128.sim/sim_1/synth/timing/xsim.dir/test_time_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/College/Thesis/AES_2018/AES_128/AES_128.sim/sim_1/synth/timing/xsim.dir/test_time_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
